#!/usr/bin/env python3
"""
Plot hash timing comparison between SHA256 and Blake3.
Reads data from data.json generated by the Rust benchmark.
"""

import json
import matplotlib.pyplot as plt
import sys
from pathlib import Path


def load_data(filepath: str = "data.json"):
    """Load timing data from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)


def plot_timings(data, output_file: str = "timing_plot.png"):
    """Plot timing comparison between the two hash algorithms."""
    
    # Extract data for SHA256
    sha_entries = data['sha256']['entries']
    sha_sizes = [e['size'] for e in sha_entries]
    sha_durations = [e['duration'] for e in sha_entries]
    
    # Extract data for Blake3
    blake_entries = data['blake3']['entries']
    blake_sizes = [e['size'] for e in blake_entries]
    blake_durations = [e['duration'] for e in blake_entries]
    
    # Create the plot
    plt.figure(figsize=(12, 6))
    
    # Plot both curves
    plt.plot(sha_sizes, sha_durations, label='SHA256', color='blue', linewidth=1.5)
    plt.plot(blake_sizes, blake_durations, label='Blake3', color='red', linewidth=1.5)
    
    # Labels and title
    plt.xlabel('Input Size (bytes)', fontsize=12)
    plt.ylabel('Duration (nanoseconds)', fontsize=12)
    plt.title('Hash Algorithm Performance Comparison', fontsize=14, fontweight='bold')
    
    # Legend
    plt.legend(fontsize=11)
    
    # Grid for better readability
    plt.grid(True, alpha=0.3, linestyle='--')
    
    # Use log scale if the range is very large
    max_duration = max(max(sha_durations), max(blake_durations))
    min_duration = min(min(sha_durations), min(blake_durations))
    if max_duration / min_duration > 100:
        plt.yscale('log')
        plt.ylabel('Duration (nanoseconds, log scale)', fontsize=12)
    
    # Tight layout to prevent label cutoff
    plt.tight_layout()
    
    # Save the plot
    plt.savefig(output_file, dpi=150, bbox_inches='tight')
    print(f"Plot saved to: {output_file}")
    
    # Show the plot
    plt.show()


def print_statistics(data):
    """Print some statistics about the data."""
    sha_entries = data['sha256']['entries']
    blake_entries = data['blake3']['entries']
    
    sha_durations = [e['duration'] for e in sha_entries]
    blake_durations = [e['duration'] for e in blake_entries]
    
    # Find switch point (where Blake3 becomes faster)
    switch_point = None
    for i, (sha, blake) in enumerate(zip(sha_durations, blake_durations)):
        if blake < sha:
            switch_point = sha_entries[i]['size']
            break
    
    print("\n" + "="*50)
    print("STATISTICS")
    print("="*50)
    print(f"Number of data points: {len(sha_entries)}")
    print(f"Input size range: {sha_entries[0]['size']} - {sha_entries[-1]['size']} bytes")
    print(f"\nSHA256 - Average: {sum(sha_durations)/len(sha_durations):.0f} ns")
    print(f"Blake3 - Average: {sum(blake_durations)/len(blake_durations):.0f} ns")
    
    if switch_point:
        print(f"\nSwitch point (Blake3 becomes faster): ~{switch_point} bytes")
    else:
        print("\nNo switch point found - Blake3 is always faster")
    print("="*50)


def main():
    # Check if a custom input file was provided
    input_file = sys.argv[1] if len(sys.argv) > 1 else "data.json"
    output_file = sys.argv[2] if len(sys.argv) > 2 else "timing_plot.png"
    
    # Check if file exists
    if not Path(input_file).exists():
        print(f"Error: {input_file} not found!")
        print(f"Usage: {sys.argv[0]} [input_json] [output_png]")
        sys.exit(1)
    
    # Load and plot data
    data = load_data(input_file)
    print_statistics(data)
    plot_timings(data, output_file)


if __name__ == "__main__":
    main()
